Repository ceph/ceph-salt, pull requests merged in 2020-07, with the labels that each got.

#277 Support registry authentication
  ceph-salt-formula/salt/ceph-salt/cleanup.sls
  ceph-salt-formula/salt/ceph-salt/container.sls
  ceph_salt/config_shell.py
  tests/test_config_shell.py
Labels: Add To Changelog, feature

#287 Improve "no minions matched" message when adding/removing minions
  ceph_salt/config_shell.py
Labels: Add To Changelog, enhancement

#293 Optimize 'ceph-salt status'
  ceph_salt/config_shell.py
  ceph_salt/salt_utils.py
Labels: Add To Changelog, performance

#283 Check 'ceph orch status' output
  ceph-salt-formula/salt/_modules/ceph_orch.py
  ceph-salt-formula/salt/_states/ceph_orch.py
Labels: Add To Changelog, bug

#270 Rely on "bootstrap" to configure MGR module
  ceph-salt-formula/salt/ceph-salt/cephbootstrap.sls
Labels: Add To Changelog, bug, needs-review

#290 Allow user to specify sudo ssh user
  ceph-salt-formula/salt/_modules/ceph_salt.py
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph-salt-formula/salt/ceph-salt/ceph-admin.sls
  ceph-salt-formula/salt/ceph-salt/cephbootstrap.sls
  ceph-salt-formula/salt/ceph-salt/sshkey.sls
  ceph_salt/config_shell.py
  ceph_salt/validate/config.py
  tests/test_config_shell.py
  tests/test_validate_config.py
Labels: Add To Changelog, feature, needs-review

#298 Only allow authentication on a single registry
  ceph-salt-formula/salt/ceph-salt/cleanup.sls
  ceph-salt-formula/salt/ceph-salt/container.sls
  ceph_salt/config_shell.py
  ceph_salt/validate/config.py
  tests/test_config_shell.py
  tests/test_validate_config.py
Labels: Add To Changelog, needs-review

#299 Drop unqualified image name support
  README.md
  ceph-salt-formula/salt/ceph-salt/files/registries.conf.j2
  ceph_salt/validate/config.py
  tests/test_validate_config.py
Labels: Add To Changelog, needs-review

#301 Install rsync
  ceph-salt-formula/salt/ceph-salt/software.sls
Labels: Add To Changelog, bug

#302 ceph-salt.spec: declare RPM dependencies
  ceph-salt.spec
Labels: Add To Changelog

#305 Install 'ceph-base' on admin minions
  ceph-salt-formula/salt/ceph-salt/cephtools.sls
Labels: Add To Changelog

#307 Refactor to support adding new salt state calls
  ceph-salt-formula/salt/_modules/ceph_salt.py
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph-salt-formula/salt/_states/ceph_salt.py
  ceph-salt-formula/salt/ceph-salt/apply/apparmor.sls
  ceph-salt-formula/salt/ceph-salt/apply/ceph-admin.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephbootstrap.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephorch.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephtools.sls
  ceph-salt-formula/salt/ceph-salt/apply/cleanup.sls
  ceph-salt-formula/salt/ceph-salt/apply/container.sls
  ceph-salt-formula/salt/ceph-salt/apply/files/chrony.conf.j2
  ceph-salt-formula/salt/ceph-salt/apply/files/chrony_sync_clock.sh
  ceph-salt-formula/salt/ceph-salt/apply/files/managed-header.txt.j2
  ceph-salt-formula/salt/ceph-salt/apply/files/registries.conf.j2
  ceph-salt-formula/salt/ceph-salt/apply/find-admin-host.sls
  ceph-salt-formula/salt/ceph-salt/apply/init.sls
  ceph-salt-formula/salt/ceph-salt/apply/provision-begin.sls
  ceph-salt-formula/salt/ceph-salt/apply/provision-end.sls
  ceph-salt-formula/salt/ceph-salt/apply/software.sls
  ceph-salt-formula/salt/ceph-salt/apply/sshkey.sls
  ceph-salt-formula/salt/ceph-salt/apply/time-prep.sls
  ceph-salt-formula/salt/ceph-salt/apply/time-sync.sls
  ceph-salt-formula/salt/ceph-salt/init.sls
  ceph_salt/__init__.py
  ceph_salt/execute.py
  tests/__init__.py
  tests/test_execute.py
Labels: refactoring

#311 chrony.conf: omit useless and counterproductive options
  ceph-salt-formula/salt/ceph-salt/apply/files/chrony.conf.j2
Labels: Add To Changelog

#306 Purge ceph clusters
  ceph-salt-formula/salt/_modules/ceph_orch.py
  ceph-salt-formula/salt/_modules/ceph_salt.py
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph-salt-formula/salt/_states/ceph_salt.py
  ceph-salt-formula/salt/ceph-salt/purge/init.sls
  ceph_salt/__init__.py
  ceph_salt/config_shell.py
  ceph_salt/execute.py
Labels: Add To Changelog, feature

#313 Handle ValueError
  ceph_salt/config_shell.py
Labels: Add To Changelog, bug

#308 cephbootstrap: run bootstrap with --apply-spec
  ceph-salt-formula/salt/ceph-salt/apply/cephbootstrap.sls
Labels: Add To Changelog, bug
