Repository ceph/ceph-salt, pull requests merged in 2020-08, with the labels that each got.

#312 SSH pub and priv key should be set via 'cephadm'
  ceph-salt-formula/salt/ceph-salt/apply/ceph-admin.sls
Labels: Add To Changelog, bug

#321 Configure 'qualified-search-registries = ["docker.io"]'
  ceph-salt-formula/salt/ceph-salt/apply/files/registries.conf.j2
Labels: Add To Changelog

#315 Make bootstrap minion optional
  ceph-salt-formula/salt/_modules/ceph_orch.py
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph-salt-formula/salt/ceph-salt/apply/ceph-admin.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephbootstrap.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephconfigure.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephtools.sls
  ceph-salt-formula/salt/ceph-salt/apply/find-admin-host.sls
  ceph-salt-formula/salt/ceph-salt/apply/init.sls
  ceph_salt/config_shell.py
  ceph_salt/execute.py
  ceph_salt/salt_utils.py
  ceph_salt/validate/config.py
  tests/__init__.py
  tests/test_validate_config.py
Labels: Add To Changelog, feature

#316 aa-teardown can fail if apparmor is disabled on the boot command line
  ceph-salt-formula/salt/ceph-salt/apply/apparmor.sls
Labels: Add To Changelog, bug

#318 Support SSH users that are configured by packages
  ceph-salt-formula/salt/_modules/ceph_salt.py
  ceph-salt-formula/salt/ceph-salt/apply/cephtools.sls
  ceph-salt-formula/salt/ceph-salt/apply/software.sls
  ceph-salt-formula/salt/ceph-salt/apply/sshkey.sls
  ceph-salt-formula/salt/macros.yml
Labels: Add To Changelog, bug

#319 Change default SSH user from 'root' to 'ceph-salt'
  ceph_salt/config_shell.py
  tests/test_config_shell.py
Labels: Add To Changelog, enhancement

#322 'cephadm' MGR module should only be enabled after cluster bootstrapped
  ceph-salt-formula/salt/ceph-salt/apply/cephconfigure.sls
Labels: Add To Changelog, bug

#295 Make use of cephadm for registry authentication
  ceph-salt-formula/salt/ceph-salt/apply/ceph-admin.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephbootstrap.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephtools.sls
  ceph-salt-formula/salt/ceph-salt/apply/cleanup.sls
  ceph-salt-formula/salt/ceph-salt/apply/container.sls
  ceph-salt-formula/salt/ceph-salt/files/registry-login-json.j2
Labels: Add To Changelog, blocked-by-cephadm

#323 Suggest 'secure=false' on custom registries configuration
  ceph_salt/config_shell.py
Labels: Add To Changelog

#291 Enable 'ceph.conf' management by cephadm
  README.md
  ceph-salt-formula/salt/ceph-salt/apply/ceph-admin.sls
Labels: Add To Changelog

#303 Add 'ceph-salt update [--reboot] [minion_id]' command
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph-salt-formula/salt/ceph-salt/update/init.sls
  ceph-salt-formula/salt/ceph-salt/update/update-begin.sls
  ceph-salt-formula/salt/ceph-salt/update/update-end.sls
  ceph-salt-formula/salt/ceph-salt/update/update.sls
  ceph-salt-formula/salt/macros.yml
  ceph_salt/__init__.py
  ceph_salt/execute.py
Labels: Add To Changelog, feature

#332 execute: check for running jobs when failing to re-apply formula
  .pylintrc
  ceph_salt/execute.py
  tests/__init__.py
Labels: bug

#345 Remove '/system_update' config
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph-salt-formula/salt/ceph-salt/apply/cephconfigure.sls
  ceph-salt-formula/salt/ceph-salt/apply/init.sls
  ceph-salt-formula/salt/ceph-salt/apply/software.sls
  ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
  ceph-salt-formula/salt/ceph-salt/update/init.sls
  ceph-salt-formula/salt/ceph-salt/update/update-begin.sls
  ceph-salt-formula/salt/ceph-salt/update/update.sls
  ceph_salt/__init__.py
  ceph_salt/config_shell.py
  ceph_salt/execute.py
  ceph_salt/validate/config.py
  tests/test_config_shell.py
  tests/test_validate_config.py
Labels: Add To Changelog

#338 tox,travis: test on Python 3.8 instead of 3.7
  .travis.yml
  tox.ini
Labels: Add To Changelog, cleanup, tests

#339 setup.py: refrain from passing "setup_cfg=True" to distutil
  setup.py
Labels: cleanup

#344 execute: write INFO message to log when stage/step begins/ends
  ceph_salt/execute.py
Labels: enhancement

#337 ceph-salt-formula/sshkey.sls: more meaningful SSH key comment
  ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
Labels: cleanup
