Repository ceph/ceph-salt, pull requests merged in 2020-10, with the labels that each got.

#422 Do the right thing in FQDN environments
  ceph-salt-formula/salt/_modules/ceph_salt.py
  ceph-salt-formula/salt/ceph-salt/apply/cephbootstrap.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephorch.sls
  ceph-salt-formula/salt/ceph-salt/apply/software.sls
  ceph-salt.spec
  ceph_salt/core.py
  ceph_salt/execute.py
Labels: feature

#423 execute: spell "Resetting" correctly
  ceph_salt/execute.py
Labels: cleanup

#428 Optimize 'ceph-salt config' and 'ceph-salt status'
  ceph_salt/config_shell.py
  ceph_salt/validate/salt_master.py
  ceph_salt/validate/salt_minion.py
  tests/test_validate_salt_master.py
Labels: performance

#429 Fix salt warning on 'ceph-salt status'
  ceph_salt/salt_utils.py
Labels: bug

#431 Inform user when default values are being populated
  ceph_salt/config_shell.py
Labels: enhancement

#430 Optimize 'ceph-salt config' minion add
  ceph_salt/core.py
  ceph_salt/salt_utils.py
  tests/__init__.py
  tests/test_config_shell.py
Labels: performance

#440 Add man page
  README.md
  ceph-salt.8
  ceph-salt.spec
Labels: documentation
