Repository ceph/ceph-salt, pull requests merged in 2020-09, with the labels that each got.

#354 execute: implement test.ping sanity check
  ceph_salt/execute.py
Labels: Add To Changelog, enhancement

#257 Install ceph-salt ssh keys on admin minions
  ceph-salt-formula/salt/_modules/ceph_salt.py
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph-salt-formula/salt/ceph-salt/apply/ceph-admin.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephbootstrap.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephconfigure.sls
  ceph-salt-formula/salt/ceph-salt/apply/cleanup.sls
  ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
  ceph-salt-formula/salt/ceph-salt/reboot/reboot-end.sls
  ceph-salt-formula/salt/ceph-salt/update/update-end.sls
Labels: Add To Changelog, feature, needs-review

#356 execute: verify whether minion nodes can resolve hostnames
  ceph-salt-formula/salt/_modules/ceph_salt.py
  ceph_salt/execute.py
Labels: Add To Changelog, enhancement

#363 Always use cephadm SSH user (and more...)
  ceph-salt-formula/salt/_modules/ceph_salt.py
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph-salt-formula/salt/ceph-salt/apply/ceph-admin.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephbootstrap.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephconfigure.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephtools.sls
  ceph-salt-formula/salt/ceph-salt/apply/cleanup.sls
  ceph-salt-formula/salt/ceph-salt/common/sshkey-cleanup.sls
  ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
  ceph-salt-formula/salt/ceph-salt/reboot/reboot-end.sls
  ceph-salt-formula/salt/ceph-salt/update/update-end.sls
  ceph-salt-formula/salt/ceph-salt/update/update.sls
  ceph-salt-formula/salt/macros.yml
  ceph_salt/config_shell.py
  ceph_salt/validate/config.py
  tests/test_config_shell.py
  tests/test_validate_config.py
Labels: Add To Changelog

#373 Fix salt event test
  tests/test_salt_event.py
Labels: tests

#367 Sanity-check time sync services when /time_server is disabled
  ceph-salt-formula/salt/_modules/ceph_salt.py
  ceph_salt/execute.py
Labels: bug

#374 Remove 'ceph-salt:execution:provisioned' grain
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph-salt-formula/salt/ceph-salt/apply/apply-begin.sls
  ceph-salt-formula/salt/ceph-salt/apply/apply-end.sls
  ceph-salt-formula/salt/ceph-salt/apply/init.sls
  ceph-salt-formula/salt/ceph-salt/apply/provision-begin.sls
  ceph-salt-formula/salt/ceph-salt/apply/provision-end.sls
Labels: cleanup

#376 Improve SSH keys stage description
  ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
Labels: enhancement

#361 Add tuned 'latency' and 'throughput' roles
  ceph_salt/config_shell.py
  ceph_salt/core.py
  ceph_salt/validate/config.py
  tests/test_config_shell.py
  tests/test_validate_config.py
Labels: Add To Changelog, feature

#380 Fix reboot in parallel with cluster running
  ceph_salt/execute.py
  ceph_salt/salt_utils.py
  tests/__init__.py
Labels: bug

#382 Readme: update diagram
  _images/architecture.odg
  _images/architecture.png
Labels: documentation

#384 Install sudo package
  ceph-salt-formula/salt/ceph-salt/apply/software.sls
  ceph-salt.spec
Labels: Add To Changelog, bug

#386 Move ceph image path config to bootstrap section
  README.md
  ceph_salt/config_shell.py
  ceph_salt/validate/config.py
  tests/test_config_shell.py
Labels: Add To Changelog, cleanup

#385 Ignore 'cephbootstrap' salt state when ceph cluster already running
  ceph-salt-formula/salt/ceph-salt/apply/cephbootstrap.sls
Labels: Add To Changelog, enhancement

#387 Cleanup tuned state files
  ceph-salt-formula/salt/ceph-salt/apply/tuned-latency.sls
  ceph-salt-formula/salt/ceph-salt/apply/tuned-off.sls
  ceph-salt-formula/salt/ceph-salt/apply/tuned-throughput.sls
Labels: cleanup

#383 Support bootstrap minion without admin role
  ceph-salt-formula/salt/_modules/ceph_salt.py
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph-salt-formula/salt/ceph-salt/apply/cephbootstrap.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephconfigure.sls
  ceph-salt-formula/salt/ceph-salt/apply/cephtools.sls
  ceph_salt/validate/config.py
  tests/test_validate_config.py
Labels: Add To Changelog

#390 Sync salt modules before using them on 'ceph-salt apply'
  ceph_salt/execute.py
  ceph_salt/validate/salt_minion.py
  tests/test_execute.py
Labels: Add To Changelog, bug

#391 Execute salt sync-all on 'ceph-salt' config and status commands
  ceph_salt/config_shell.py
Labels: bug

#398 Retry SSH 'host add' execution on connection closed
  ceph-salt-formula/salt/_modules/ceph_salt.py
  ceph-salt-formula/salt/_states/ceph_orch.py
Labels: enhancement

#399 Fix salt warn when 'ceph-salt config' is executed for the first time
  ceph_salt/validate/salt_minion.py
Labels: enhancement

#400 Install 'sudo' before 'sudoers' configuration
  ceph-salt-formula/salt/ceph-salt/apply/software.sls
  ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
Labels: bug

#395 Change cephadm bootstrap output redirect file
  ceph-salt-formula/salt/ceph-salt/apply/cephbootstrap.sls
Labels: bug

#401 Validate '/cephadm_bootstrap/mon_ip'
  ceph_salt/config_shell.py
  ceph_salt/core.py
  ceph_salt/execute.py
  ceph_salt/validate/config.py
  tests/test_validate_config.py
Labels: enhancement

#407 Restart 'chronyd' service to apply chrony config
  ceph-salt-formula/salt/ceph-salt/apply/time-prep.sls
Labels: bug

#403 Validate duplicated registries
  ceph_salt/validate/config.py
  tests/test_validate_config.py
Labels: enhancement

#408 Display 'stderr' on stage/step failure
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph_salt/execute.py
Labels: bug

#404 Add 'ceph-salt stop' command
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph-salt-formula/salt/_states/ceph_salt.py
  ceph-salt-formula/salt/ceph-salt/apply/apply-begin.sls
  ceph-salt-formula/salt/ceph-salt/apply/init.sls
  ceph-salt-formula/salt/ceph-salt/purge/init.sls
  ceph-salt-formula/salt/ceph-salt/reboot/init.sls
  ceph-salt-formula/salt/ceph-salt/reboot/reboot-begin.sls
  ceph-salt-formula/salt/ceph-salt/reset.sls
  ceph-salt-formula/salt/ceph-salt/stop/init.sls
  ceph-salt-formula/salt/ceph-salt/stop/stop-end.sls
  ceph-salt-formula/salt/ceph-salt/stop/stop.sls
  ceph-salt-formula/salt/ceph-salt/update/update-begin.sls
  ceph_salt/__init__.py
  ceph_salt/execute.py
Labels: feature

#411 Handle unresponsive minions properly
  ceph_salt/config_shell.py
  ceph_salt/execute.py
  ceph_salt/salt_utils.py
  tests/__init__.py
Labels: bug
