Repository ceph/ceph-salt, pull requests merged in 2020-06, with the labels that each got.

#253 Allow users to provide their dashboard cert for bootstrap
  ceph_salt/config_shell.py
  ceph_salt/validate/config.py
  tests/test_config_shell.py
  tests/test_validate_config.py
Labels: Add To Changelog, feature

#255 Report log file location on exit
  ceph_salt/apply.py
Labels: Add To Changelog, enhancement

#254 Switch to reactive UI refresh after execution is complete
  ceph_salt/apply.py
Labels: Add To Changelog, enhancement

#259 Add "Conflicts: deepsea" to spec file
  ceph-salt.spec
Labels: Add To Changelog

#263 Don't log scrollbar info when rendering scrollbar
  ceph_salt/apply.py
Labels: Add To Changelog, cleanup

#268 container: make step/stage descriptions more descriptive
  ceph-salt-formula/salt/ceph-salt/container.sls
Labels: Add To Changelog

#264 configshell: Handle execution errors on command line
  ceph_salt/config_shell.py
Labels: bug, cleanup

#269 Allow to re-apply config
  ceph-salt-formula/salt/_states/ceph_salt.py
  ceph-salt-formula/salt/ceph-salt/ceph-admin.sls
  ceph_salt/apply.py
  tests/test_apply.py
Labels: Add To Changelog, feature

#262 Allow users to disable custom registries configuration
  ceph-salt-formula/salt/ceph-salt/container.sls
  ceph_salt/config_shell.py
  tests/test_config_shell.py
Labels: Add To Changelog, feature

#276 Optimize "ceph_orch.wait_for_admin_host" state
  ceph-salt-formula/salt/_modules/ceph_orch.py
  ceph-salt-formula/salt/_states/ceph_orch.py
Labels: Add To Changelog, performance

#271 Reduce the number of remote grain requests
  ceph-salt-formula/salt/_states/ceph_orch.py
  ceph-salt-formula/salt/_states/ceph_salt.py
Labels: Add To Changelog, performance

#278 Fix log location message
  ceph_salt/__init__.py
  ceph_salt/apply.py
  ceph_salt/logging_utils.py
Labels: Add To Changelog, bug

#282 README: avoid `:latest` tag.
  README.md
Labels: documentation
