Repository ceph/ceph-salt, pull requests merged in 2020-05, with the labels that each got.

#211 Store minion_id in pillar instead of hostname
  README.md
  ceph_salt/apply.py
  ceph_salt/config_shell.py
  ceph_salt/core.py
  ceph_salt/validate/config.py
  tests/test_config_shell.py
  tests/test_deploy.py
  tests/test_validate_config.py
Labels: Add To Changelog, cleanup

#207 Wait for admin should fail if any admin failed
  ceph-salt-formula/salt/_states/ceph_orch.py
Labels: Add To Changelog, bug

#212 Rename test from deploy to apply
  tests/test_apply.py
Labels: tests

#206 time: support time server not managed by ceph-salt
  README.md
  ceph-salt-formula/metadata/pillar.example
  ceph-salt-formula/salt/ceph-salt/files/chrony.conf.j2
  ceph-salt-formula/salt/ceph-salt/time-sync.sls
  ceph_salt/config_shell.py
  ceph_salt/salt_utils.py
  ceph_salt/validate/config.py
  tests/test_validate_config.py
Labels: Add To Changelog, feature

#216 Log warn when public IP is loopback IP ('127.0.0.1')
  ceph_salt/core.py
Labels: Add To Changelog, ceph-salt, cleanup

#221 Fix error running `status` with empty pillar data
  ceph_salt/config_shell.py
Labels: Add To Changelog, bug

#219 Default values are now persisted in pillar data
  ceph-salt-formula/salt/ceph-salt/cephbootstrap.sls
  ceph-salt-formula/salt/ceph-salt/software.sls
  ceph-salt-formula/salt/ceph-salt/time-prep.sls
  ceph-salt-formula/salt/ceph-salt/time-sync.sls
  ceph_salt/config_shell.py
  ceph_salt/validate/config.py
  tests/test_config_shell.py
  tests/test_validate_config.py
Labels: Add To Changelog

#224 Improve "ceph-salt config" performance
  ceph_salt/core.py
Labels: Add To Changelog, performance

#227 User feedback when adding/removing minions
  ceph_salt/config_shell.py
Labels: Add To Changelog, enhancement, performance

#228 salt_utils: don't log dashboard password
  ceph_salt/salt_utils.py
Labels: bug

#230 Optimize remote grain get
  ceph-salt-formula/salt/_modules/ceph_salt.py
Labels: Add To Changelog, performance

#220 Unable to see dashboard password
  ceph-salt-formula/salt/ceph-salt/cephbootstrap.sls
  ceph_salt/config_shell.py
  ceph_salt/validate/config.py
  tests/test_config_shell.py
  tests/test_validate_config.py
Labels: Add To Changelog

#233 chrony_sync_clock: wait longer for sync
  ceph-salt-formula/salt/ceph-salt/files/chrony_sync_clock.sh
Labels: Add To Changelog, bug

#234 Do not log pillar data secrets
  ceph_salt/salt_utils.py
Labels: Add To Changelog, bug

#235 Add 'cephadm' role
  README.md
  ceph-salt-formula/salt/ceph-salt/cephorch.sls
  ceph-salt-formula/salt/ceph-salt/cephtools.sls
  ceph-salt-formula/salt/ceph-salt/find-admin-host.sls
  ceph_salt/config_shell.py
  ceph_salt/core.py
  ceph_salt/validate/config.py
  tests/test_config_shell.py
  tests/test_validate_config.py
Labels: Add To Changelog, feature

#239 chrony_sync_clock.sh: run first chronyc in try-wait loop
  ceph-salt-formula/salt/ceph-salt/files/chrony_sync_clock.sh
Labels: Add To Changelog, bug

#244 Persist journal logs
  ceph-salt-formula/salt/ceph-salt/software.sls
Labels: Add To Changelog

#247 apply: probe external time servers (V2)
  ceph-salt-formula/salt/_modules/ceph_salt.py
  ceph-salt.spec
  ceph_salt/apply.py
Labels: Add To Changelog, enhancement

#243 Support SSH keys import and export
  README.md
  ceph_salt/config_shell.py
  ceph_salt/core.py
  ceph_salt/validate/config.py
  tests/test_config_shell.py
  tests/test_validate_config.py
Labels: Add To Changelog, feature

#249 Fix python3-ntplib required version
  ceph-salt.spec
Labels: Add To Changelog, bug

#251 README: time sync is optional for ceph-salt, required for cephadm
  README.md
Labels: documentation
